const child = document.createElement("div");
child.class="child";
const image=document.createElement("img");
image.src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1496969351i/35391707.jpg";
image.width="150";
image.height="150";
const h4=document.createElement("h4");
h4.innerText="Price: 350/-";
child.append(image);
child.append(h4);
const parent=document.getElementById("root");
parent.appendchild(child);